### ISSUE TITLE
Project Will Not Build

### ISSUE THREAD

**Issue by jeffbrown** [orubel/api-framework-example#4]
If you add `maven { url 'https://dl.bintray.com/nosegrind/plugins' }` below https://github.com/orubel/api-framework-example/blob/b25f5be7df69365626188241394d182d1fbb8a9f/build.gradle#L40 then folks will be able to build the project without having to build the `api-framework` plugin locally first.  As it is right now, the build cannot resolve the plugin because it isn't available in `mavenLocal()` or `https://repo.grails.org/grails/core` which are the only 2 repositories configured in `build.gradle`.  The plugin docs should probably include that detail as well.

**Comment by orubel** [comment]
Oh. Hmmm... I thought it was mavenCentral(). I must just be seeing this because of local build *smack*. Thank you. Adding and pushing now.

**Comment by orubel** [comment]
Again, thank you very much. 

Have added code change.

**Comment by orubel** [comment]
Jeff,

I also just updated the documentation as well to make sure it denotes BETA should use this repository. Thank you again.
